name: Merge Dependabot PRs automatically
description: Create a `@dependabot merge` comment for successfully checked PRs
branding:
  icon: "check-square"
  color: "green"
inputs:
  token:
    description: Github token for user with push permissions on the repo
    required: true
  run-id:
    description: Workflow run ID
    required: true
  only-success:
    description: |
      If all workflow runs must be successful. By default workflows that are skipped are ignored, but to require everything to be successful
      you can set this option.
    required: false
  only-given-run:
    description: |
      Only use the provided run ID's check suite. By default all check suites for the PR are considered when creating the comment.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
