name: Add Dependabot merge comment
description: |
  Given a workflow run ID, determine if the run was successful and if the related PR
  was created by Dependabot. If it is, create a `@dependabot merge` comment.

  The user who creates the comment must have push permission for the repository.
inputs:
  token:
    description: Github token for user with push permissions on the repo
    required: true
  run-id:
    description: Workflow run ID
    required: true
runs:
  using: node12
  main: index.js